config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :subjects
  resources :chats
  resources :users
  resources :tutors
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/get' => 'pages#get'
  get '/faq' => 'pages#faq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :number_of_topics
  has_many :total_hours
  has_and_belongs_to_many :tutors
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  has_many :years_of_experience
  has_and_belongs_to_many :subjects
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :subjects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? # Log out non-existent users
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @chats = Chat.all
  end

  def new
    @chats = Chat.new
  end

  def create
    @chat = Chat.new user_params
    if @chat.save
      session[:chat_id] = @chat.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def chat_params
    params.require(:chat).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def get
  end

  def faq
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @subject = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      session[:user_id] = @user.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def subject_params
    params.require(:subject).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subject = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def show
    @subject = Subject.find params[:id]

  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      session[:user_id] = @user.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def subject_params
    params.require(:subject).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController


  def index
    @tutors = Tutor.all
  end

  def new
    @tutors = Tutor.new
  end

  def show
    @tutors = Tutor.find params[:id]

  end

  def create
    @tutors = Tutor.new tutor_params
    if @tutor.save
      session[:tutor_id] = @tutor.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def tutor_params
    params.require(:tutor).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path # You can redirect wherever you like.
    else
      render :new # show them the form again and let them have another go.
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="w-100 py-4 flex-shrink-0 footer mt-5" >
  <div class="container py-4">
    <div class="row gy-4 gx-5">
      <div class="col-lg-4 col-md-6">
        <h5 class="h1 text-white">Law Law Land</h5>
        <p class="small text-muted">Your go to legal help one stop shop.</p>
        <p class="small text-muted mb-0">&copy; Copyright. All rights reserved.</p>
      </div>
      <div class="col-lg-2 col-md-6">
        <h5 class="text-white mb-3">Quick links</h5>
        <ul class="list-unstyled text-muted">
          <li><a href="/home">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/get">Get started</a></li>
          <li><a href="/faq">FAQ</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6">
      </div>
      <div class="col-lg-4 col-md-6">
        <h5 class="text-white mb-3">Newsletter</h5>
        <p class="small text-muted">Stay legally plugged.🔌</p>
        <form action="#">
          <div class="input-group mb-3">
            <input class="form-control" type="text" placeholder="Email address" aria-label="email address" aria-describedby="button-addon2">
            <button class="btn btn-primary" id="button-addon2" type="button">Submit<i class="fas fa-paper-plane"></i></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container navigation">
  <div class="row">
    <div class="col-12 pt-3 pb-1">
      <div class="float-end">
        <% if @current_user.present? %>
        <div class="dropdown show">
          <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @current_user.name %>
          </a>
          <div class="container">
            <nav>
              <%= link_to 'Home', root_path %>
              <% if @current_user.present? %>
              <%= link_to "Log out #{ @current_user.email }", login_path, :method => 'delete' %>
              <% else %>
              <%= link_to 'Sign up', new_user_path %>
              <%= link_to 'Sign in', login_path %>
              <% end %>
            </nav>
          </div>
        </div>
        <% else %>
        <%= link_to "Log In", login_path, class: "btn btn-outline-primary" %>
        <%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class ="logo-container">
        <img class="home-logo" src="https://scontent-syd2-1.xx.fbcdn.net/v/t1.18169-9/14355038_117843045342969_2416252482737794925_n.jpg?_nc_cat=109&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=iVxj7CcIPlQAX9ge8u-&_nc_ht=scontent-syd2-1.xx&oh=23fa9a3c64d7b607979668d12589eb03&oe=61A009BE" alt=""></div>
        <p class="h5 mb-4 text-center"><%= link_to "Home", root_path %> | <%= link_to "Subjects", subjects_path %> | <%= link_to "Tutors", tutors_path %></p>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Legal Plug</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="the-body">

  <%= render partial: "layouts/header" %>

  <section class="">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 pt-4">
          <%= yield %>
        </div>
      </div>
    </div>
  </section>

  <%= render partial: "layouts/footer" %>


</body>
</html>

app/views/pages/about.html.erb
<h1>About The Legal Plug </h1>

app/views/pages/faq.html.erb
<h2>Frequently Asked Questions</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Vitae tortor condimentum lacinia quis vel eros donec. Augue ut lectus arcu bibendum at varius. Etiam non quam lacus suspendisse faucibus interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Enim tortor at auctor urna nunc id cursus metus. In aliquam sem fringilla ut. Quam adipiscing vitae proin sagittis. Suspendisse sed nisi lacus sed viverra tellus. Eget egestas purus viverra accumsan in nisl nisi. Massa tincidunt dui ut ornare lectus sit amet est placerat. Viverra ipsum nunc aliquet bibendum enim facilisis. Id semper risus in hendrerit gravida rutrum quisque non. Egestas pretium aenean pharetra magna ac. Feugiat vivamus at augue eget arcu dictum varius. Gravida dictum fusce ut placerat orci.

Enim diam vulputate ut pharetra sit amet aliquam id diam. Gravida neque convallis a cras. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Eget arcu dictum varius duis at consectetur lorem donec massa. Lectus mauris ultrices eros in cursus turpis. Morbi tristique senectus et netus et malesuada fames. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Ac turpis egestas maecenas pharetra convallis. Ac odio tempor orci dapibus ultrices in. Nibh venenatis cras sed felis eget velit aliquet sagittis. Pellentesque nec nam aliquam sem et tortor consequat.

Risus quis varius quam quisque id diam vel quam. Vestibulum lorem sed risus ultricies. Egestas quis ipsum suspendisse ultrices. Eget lorem dolor sed viverra ipsum nunc. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Diam quam nulla porttitor massa id neque aliquam. Et malesuada fames ac turpis egestas sed tempus urna et. Quam quisque id diam vel. Id faucibus nisl tincidunt eget nullam non nisi. Quam viverra orci sagittis eu volutpat. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Bibendum arcu vitae elementum curabitur vitae. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Pharetra vel turpis nunc eget lorem dolor.

Laoreet sit amet cursus sit amet dictum sit amet justo. Euismod in pellentesque massa placerat duis ultricies. Eu consequat ac felis donec et odio pellentesque diam. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. In ante metus dictum at. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Cursus mattis molestie a iaculis at erat. Natoque penatibus et magnis dis parturient montes. Velit euismod in pellentesque massa. Nisl condimentum id venenatis a condimentum. Urna id volutpat lacus laoreet. Tristique sollicitudin nibh sit amet commodo nulla. Tellus in hac habitasse platea dictumst. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Sed elementum tempus egestas sed.

Mi sit amet mauris commodo quis imperdiet massa tincidunt. Porttitor massa id neque aliquam vestibulum morbi blandit. Risus feugiat in ante metus dictum at tempor. Ut placerat orci nulla pellentesque dignissim enim sit amet. Hac habitasse platea dictumst quisque sagittis purus sit. Pharetra vel turpis nunc eget lorem. Pellentesque pulvinar pellentesque habitant morbi. Vel quam elementum pulvinar etiam non quam lacus. Etiam tempor orci eu lobortis elementum. Nunc vel risus commodo viverra. Ultricies tristique nulla aliquet enim. Nulla facilisi nullam vehicula ipsum. Lorem ipsum dolor sit amet consectetur adipiscing. Sed risus pretium quam vulputate. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam.</p>

app/views/pages/get.html.erb
<h2>How to get started as a tutor</h2>

<p>  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Vitae tortor condimentum lacinia quis vel eros donec. Augue ut lectus arcu bibendum at varius. Etiam non quam lacus suspendisse faucibus interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Enim tortor at auctor urna nunc id cursus metus. In aliquam sem fringilla ut. Quam adipiscing vitae proin sagittis. Suspendisse sed nisi lacus sed viverra tellus. Eget egestas purus viverra accumsan in nisl nisi. Massa tincidunt dui ut ornare lectus sit amet est placerat. Viverra ipsum nunc aliquet bibendum enim facilisis. Id semper risus in hendrerit gravida rutrum quisque non. Egestas pretium aenean pharetra magna ac. Feugiat vivamus at augue eget arcu dictum varius. Gravida dictum fusce ut placerat orci.

Enim diam vulputate ut pharetra sit amet aliquam id diam. Gravida neque convallis a cras. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Eget arcu dictum varius duis at consectetur lorem donec massa. Lectus mauris ultrices eros in cursus turpis. Morbi tristique senectus et netus et malesuada fames. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Ac turpis egestas maecenas pharetra convallis. Ac odio tempor orci dapibus ultrices in. Nibh venenatis cras sed felis eget velit aliquet sagittis. Pellentesque nec nam aliquam sem et tortor consequat.

Risus quis varius quam quisque id diam vel quam. Vestibulum lorem sed risus ultricies. Egestas quis ipsum suspendisse ultrices. Eget lorem dolor sed viverra ipsum nunc. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Diam quam nulla porttitor massa id neque aliquam. Et malesuada fames ac turpis egestas sed tempus urna et. Quam quisque id diam vel. Id faucibus nisl tincidunt eget nullam non nisi. Quam viverra orci sagittis eu volutpat. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Bibendum arcu vitae elementum curabitur vitae. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Pharetra vel turpis nunc eget lorem dolor.

Laoreet sit amet cursus sit amet dictum sit amet justo. Euismod in pellentesque massa placerat duis ultricies. Eu consequat ac felis donec et odio pellentesque diam. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. In ante metus dictum at. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Cursus mattis molestie a iaculis at erat. Natoque penatibus et magnis dis parturient montes. Velit euismod in pellentesque massa. Nisl condimentum id venenatis a condimentum. Urna id volutpat lacus laoreet. Tristique sollicitudin nibh sit amet commodo nulla. Tellus in hac habitasse platea dictumst. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Sed elementum tempus egestas sed.

Mi sit amet mauris commodo quis imperdiet massa tincidunt. Porttitor massa id neque aliquam vestibulum morbi blandit. Risus feugiat in ante metus dictum at tempor. Ut placerat orci nulla pellentesque dignissim enim sit amet. Hac habitasse platea dictumst quisque sagittis purus sit. Pharetra vel turpis nunc eget lorem. Pellentesque pulvinar pellentesque habitant morbi. Vel quam elementum pulvinar etiam non quam lacus. Etiam tempor orci eu lobortis elementum. Nunc vel risus commodo viverra. Ultricies tristique nulla aliquet enim. Nulla facilisi nullam vehicula ipsum. Lorem ipsum dolor sit amet consectetur adipiscing. Sed risus pretium quam vulputate. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam.</p>

<h2>How to get started as a student</h2>

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Vitae tortor condimentum lacinia quis vel eros donec. Augue ut lectus arcu bibendum at varius. Etiam non quam lacus suspendisse faucibus interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Enim tortor at auctor urna nunc id cursus metus. In aliquam sem fringilla ut. Quam adipiscing vitae proin sagittis. Suspendisse sed nisi lacus sed viverra tellus. Eget egestas purus viverra accumsan in nisl nisi. Massa tincidunt dui ut ornare lectus sit amet est placerat. Viverra ipsum nunc aliquet bibendum enim facilisis. Id semper risus in hendrerit gravida rutrum quisque non. Egestas pretium aenean pharetra magna ac. Feugiat vivamus at augue eget arcu dictum varius. Gravida dictum fusce ut placerat orci.

Enim diam vulputate ut pharetra sit amet aliquam id diam. Gravida neque convallis a cras. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Eget arcu dictum varius duis at consectetur lorem donec massa. Lectus mauris ultrices eros in cursus turpis. Morbi tristique senectus et netus et malesuada fames. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Ac turpis egestas maecenas pharetra convallis. Ac odio tempor orci dapibus ultrices in. Nibh venenatis cras sed felis eget velit aliquet sagittis. Pellentesque nec nam aliquam sem et tortor consequat.

Risus quis varius quam quisque id diam vel quam. Vestibulum lorem sed risus ultricies. Egestas quis ipsum suspendisse ultrices. Eget lorem dolor sed viverra ipsum nunc. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Diam quam nulla porttitor massa id neque aliquam. Et malesuada fames ac turpis egestas sed tempus urna et. Quam quisque id diam vel. Id faucibus nisl tincidunt eget nullam non nisi. Quam viverra orci sagittis eu volutpat. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Bibendum arcu vitae elementum curabitur vitae. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Pharetra vel turpis nunc eget lorem dolor.

Laoreet sit amet cursus sit amet dictum sit amet justo. Euismod in pellentesque massa placerat duis ultricies. Eu consequat ac felis donec et odio pellentesque diam. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. In ante metus dictum at. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Cursus mattis molestie a iaculis at erat. Natoque penatibus et magnis dis parturient montes. Velit euismod in pellentesque massa. Nisl condimentum id venenatis a condimentum. Urna id volutpat lacus laoreet. Tristique sollicitudin nibh sit amet commodo nulla. Tellus in hac habitasse platea dictumst. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Sed elementum tempus egestas sed.

Mi sit amet mauris commodo quis imperdiet massa tincidunt. Porttitor massa id neque aliquam vestibulum morbi blandit. Risus feugiat in ante metus dictum at tempor. Ut placerat orci nulla pellentesque dignissim enim sit amet. Hac habitasse platea dictumst quisque sagittis purus sit. Pharetra vel turpis nunc eget lorem. Pellentesque pulvinar pellentesque habitant morbi. Vel quam elementum pulvinar etiam non quam lacus. Etiam tempor orci eu lobortis elementum. Nunc vel risus commodo viverra. Ultricies tristique nulla aliquet enim. Nulla facilisi nullam vehicula ipsum. Lorem ipsum dolor sit amet consectetur adipiscing. Sed risus pretium quam vulputate. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam.

app/views/pages/home.html.erb
<div class="row welcome-page">
  <div class="col-md-12">
    <h1>Welcome To The Legal Plug <% if @current_user.present? %><%= @current_user.name %><%end%></h1>
  </div>
</div>

<div class="row welcome-page">

  <div class="container text">

    <h1 class="display-4">Your go to law tutor directory</h1>
    <p class="lead">Best place to find an affordable tutor for any of your priestly 11 subjects.</p>
    <hr class="my-4">
    <p>Australia's most popular student platform, built just for you.</p>
    <a class="btn btn-primary btn-lg" href="/users/new" role="button">Sign up Today!</a>

  </div>

</div>

app/views/session/new.html.erb
<h1>Log In</h1>

<%= form_tag login_path do %>
<div class="form-group">
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag :password %>
  <%= password_field_tag :password, nil, :class => 'form-control' %>
</div>

<%= submit_tag 'Sign in', :class => 'btn btn-info btn-lg' %>
<% end %>

app/views/subjects/edit.html.erb
<h1>Subject#edit</h1>
<p>Find me in app/views/subject/edit.html.erb</p>

app/views/subjects/index.html.erb
<h2>List of Subjects</h2>

<ul class="list-group">
  <% @subject.each do |subject| %>
  <li class="list-group-item">
    <p class = "subject">

      <%= link_to subject.name, subject_path(subject.id) %>
    </p>
  </li>
  <% end %>
</ul>

app/views/subjects/search.html.erb
<%= form_tag(subject_path, method: :get) do %>
<%= text_field_tag :name %>
<%= submit_tag 'Search' %>
<% end %>

app/views/subjects/show.html.erb
<div class="row mt-3">
  <div class="col-lg-12 text-center">
    <h1><%= @subject.name %></h1>

    <div class="justify-content-center">
      <%= link_to "Back To Subjects", subjects_path, :class => "btn btn-outline-info mr-3 mt-3" %>
      <%= link_to "Edit Subject", edit_subject_path(@subject.id), :class => "btn btn-outline-warning mr-3 mt-3"%>
      <%= link_to "Delete Subject", subject_path(@subject.id), :method => "delete", :class => "btn btn-outline-danger mt-3", data: {confirm: "Are you sure?"}%>
    </div>

    <div class="row mt-4">
      <div class="col-md-4">
        <p class="lead"><%= @subject.name %>'s Info</p>
        <p><span class="subject-info"><strong>Name:</strong></span> <%= @subject.name %> </p>
        <p><span class="subject-info"><strong>Available Tutors:</strong></span> </p>
        <% @subject.tutors.each do |tutor| %>
        <p class = "tutor">
          <%= link_to tutor.name, tutor_path(tutor.id) %>
        </p>
        <% end %>
      </div>

app/views/tutors/_form.html.erb
<%= form_for @tutors do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :subject %>
    <%= f.text_field :subject %>

    <%= f.label :bio %>
    <%= f.text_field :bio %>

    <%= f.label :image %>
    <%= f.url_field :image %>

    <%= f.submit %>
<% end %>

app/views/tutors/edit.html.erb
<h1>Edit Tutor</h1>

<%= render :partial => 'form' %>

app/views/tutors/index.html.erb
<h2> List of Available Tutors </h2>

<ul class="list-group">
  <% @tutors.each do |tutor| %>

  <li class="list-group-item">
    <p class = "tutor">
      <%= image_tag tutor.image, :class  => "tutor_image" %>

      <%= link_to tutor.name, tutor_path(tutor.id) %>
    </p>


  </li>

  <% end %>
</ul>

<%= link_to "Add New Tutor", new_tutor_path, :class => "btn btn-outline-info" %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render :partial => 'form' %>

app/views/tutors/show.html.erb
<div class="tutor-profile">
  <h1 class="pb-4"><%= @tutors.name %></h1>

  <%= image_tag @tutors.image, :class => 'feature pb-5 tutor_image' %>

  <ul>
    <li><strong>Name:</strong> <%= @tutors.name %></li>
    <li><strong>Subject:</strong> <%= @tutors.subject %></li>
    <li><strong>What students say:</strong> <%= @tutors.bio %> </li>

    <% @tutors.subjects.each do |subject| %>
    <% end %>
  </ul>


  <div class="controls m-3 float-end">
    <%= button_to "Edit Tutor", edit_tutor_path(@tutors.id), :method => 'get' %><br>
    <%= button_to "Delete Tutor", @tutor, :method => 'delete', :data => { :confirm => 'Are you sure?'} %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="form-group mt-3">
        <%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.email_field :email, :class => true , :class => "form-control"%>
        <%= f.label :password, :class => "mt-3"%>
        <%= f.password_field :password, :class => "form-control "%>
        <br />
        <%= f.submit "Update User", class: 'btn btn-outline-warning mt-3'  %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<h2><%= User.count %> users</h2>
<% @users.each do |user| %>
  <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ol>
<% end %>
<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :class => 'form-control' %>
</div>

<%= f.submit "Sign up!", :class => 'btn btn-info' %>
<% end %>